package com.test.summer.authorization.dao.sys;
import com.test.summer.authorization.entity.sys.SysMenuPermission;

/**
 * @author zengfeiyue
 */
public interface SysMenuPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    int insert(SysMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    int insertSelective(SysMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    SysMenuPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMenuPermission record);
}