package com.summer.gateway.dao.sys;


import com.summer.gateway.entity.sys.SysGroup;
import com.test.summer.gateway.entity.sys.SysGroup;

public interface SysGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int insert(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int insertSelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    SysGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGroup record);
}